# tests.py
"""
Router.register('books', BookViewSet) 가 자동 생성한 7 개 URL 검증.

실행:
    python manage.py test book_app -v 2

검증 대상 (이 7 개 URL 이 자동으로 만들어진다):
    1) GET    /api/v3/books/                → list
    2) POST   /api/v3/books/                → create
    3) GET    /api/v3/books/<pk>/           → retrieve
    4) PUT    /api/v3/books/<pk>/           → update
    5) PATCH  /api/v3/books/<pk>/           → partial_update
    6) DELETE /api/v3/books/<pk>/           → destroy
    7) POST   /api/v3/books/<pk>/toggle/    → toggle (@action 커스텀)
"""
from django.test         import TestCase
from django.urls         import reverse
from rest_framework      import status
from rest_framework.test import APIClient

from .models import Book


class RouterAutoGeneratedURLsTest(TestCase):
    """
    Router 가 BookViewSet 으로부터 자동 등록한 모든 URL 을 검증.

    검증 방식 두 단계:
      A) reverse() 로 'URL 이름' 이 등록되었는지 확인
         → Router 가 정말로 URL 패턴을 만들었음을 증명
      B) APIClient 로 각 URL 을 호출해 응답 상태와 ViewSet 메서드 동작 확인
         → URL 이 올바른 ViewSet 메서드로 라우팅됨을 증명
    """

    @classmethod
    def setUpTestData(cls):
        """테스트 전체에서 공유할 도서 1 건 생성."""
        cls.book = Book.objects.create(
            title="DRF 실전",
            author="홍길동",
            published_year=2024,
            is_available=True,
        )

    def setUp(self):
        self.client = APIClient()

    # =====================================================================
    # A) URL 자동 등록 확인 — reverse() 로 검증
    # =====================================================================

    def test_01_list_url_registered_as_book_list(self):
        """Router 가 'book-list' 이름으로 /api/v3/books/ 를 등록했는가"""
        url = reverse('book-list')
        self.assertEqual(url, '/api/v3/books/')

    def test_02_detail_url_registered_as_book_detail(self):
        """Router 가 'book-detail' 이름으로 /api/v3/books/<pk>/ 를 등록했는가"""
        url = reverse('book-detail', kwargs={'pk': self.book.pk})
        self.assertEqual(url, f'/api/v3/books/{self.book.pk}/')

    def test_03_action_url_registered_as_book_toggle(self):
        """@action 데코레이터가 'book-toggle' 이름으로 URL 을 추가했는가"""
        url = reverse('book-toggle', kwargs={'pk': self.book.pk})
        self.assertEqual(url, f'/api/v3/books/{self.book.pk}/toggle/')

    # =====================================================================
    # B) 각 HTTP 메서드 → ViewSet 메서드 라우팅 확인
    # =====================================================================

    def test_04_GET_list_returns_book_array(self):
        """GET /api/v3/books/  →  list()"""
        response = self.client.get('/api/v3/books/')
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertIsInstance(response.data, list)
        self.assertGreaterEqual(len(response.data), 1)

    def test_05_POST_creates_new_book(self):
        """POST /api/v3/books/  →  create()"""
        before = Book.objects.count()
        response = self.client.post('/api/v3/books/', {
            'title':          '점프 투 장고',
            'author':         '박응용',
            'published_year': 2022,
            'is_available':   True,
        }, format='json')
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Book.objects.count(), before + 1)
        self.assertEqual(response.data['title'], '점프 투 장고')

    def test_06_GET_detail_returns_single_book(self):
        """GET /api/v3/books/<pk>/  →  retrieve()"""
        response = self.client.get(f'/api/v3/books/{self.book.pk}/')
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data['title'], 'DRF 실전')

    def test_07_PUT_replaces_book(self):
        """PUT /api/v3/books/<pk>/  →  update()  — 전체 필드 교체"""
        response = self.client.put(
            f'/api/v3/books/{self.book.pk}/',
            {
                'title':          'DRF 실전 (개정판)',
                'author':         '홍길동',
                'published_year': 2025,
                'is_available':   False,
            },
            format='json',
        )
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.book.refresh_from_db()
        self.assertEqual(self.book.title, 'DRF 실전 (개정판)')
        self.assertEqual(self.book.published_year, 2025)

    def test_08_PATCH_partially_updates_book(self):
        """PATCH /api/v3/books/<pk>/  →  partial_update()  — 일부 필드만"""
        response = self.client.patch(
            f'/api/v3/books/{self.book.pk}/',
            {'is_available': False},
            format='json',
        )
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.book.refresh_from_db()
        self.assertFalse(self.book.is_available)

    def test_09_DELETE_removes_book(self):
        """DELETE /api/v3/books/<pk>/  →  destroy()"""
        response = self.client.delete(f'/api/v3/books/{self.book.pk}/')
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertFalse(Book.objects.filter(pk=self.book.pk).exists())

    def test_10_POST_toggle_action_flips_is_available(self):
        """POST /api/v3/books/<pk>/toggle/  →  @action toggle()"""
        original = self.book.is_available
        response = self.client.post(f'/api/v3/books/{self.book.pk}/toggle/')
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.book.refresh_from_db()
        self.assertEqual(self.book.is_available, not original)
        self.assertEqual(response.data['is_available'], not original)

    # =====================================================================
    # C) 허용되지 않은 메서드 거부 확인 (Router 의 라우팅 정확성 증명)
    # =====================================================================

    def test_11_PUT_on_list_url_returns_405(self):
        """PUT /api/v3/books/  — list URL 에 PUT 은 정의 안 됨"""
        response = self.client.put('/api/v3/books/')
        self.assertEqual(response.status_code, status.HTTP_405_METHOD_NOT_ALLOWED)

    def test_12_GET_on_toggle_action_returns_405(self):
        """GET /api/v3/books/<pk>/toggle/  — toggle 은 POST 만 허용"""
        response = self.client.get(f'/api/v3/books/{self.book.pk}/toggle/')
        self.assertEqual(response.status_code, status.HTTP_405_METHOD_NOT_ALLOWED)

    def test_13_DELETE_on_list_url_returns_405(self):
        """DELETE /api/v3/books/  — list URL 에 DELETE 는 정의 안 됨"""
        response = self.client.delete('/api/v3/books/')
        self.assertEqual(response.status_code, status.HTTP_405_METHOD_NOT_ALLOWED)
