# Generated by Django 4.2.30 on 2026-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('published_year', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '도서',
                'verbose_name_plural': '도서 목록',
                'ordering': ['-id'],
            },
        ),
    ]
